import json, pathlib, hashlib, csv
from collections import Counter
D=pathlib.Path('/home/gaoym/when-consensus-lies-v8-zero-call-20260925/v9_cst_pecr_zero_call/pecr_evidence_audit_v1_20260929')
flow=json.load(open(D/'reports/QUEUE_FLOW.json')); met=json.load(open(D/'reports/OOF_NUMERIC_RECHECK.json'))
rows=[json.loads(x) for x in open(D/'data/item_coverage_audit.jsonl')]
# Failure detail
c=Counter()
for r in rows:
 if r['candidate']:
  for w,reason in r['parse_reasons'].items():
   if reason:c[f'{w}:{reason}']+=1
json.dump({'candidate_parse_reason_occurrences':c},open(D/'reports/PARSE_REASON_COUNTS.json','w'),indent=2)
# Queue table
s=['# PECR queue-flow audit (read-only)', '', '| Stage | Items | Source groups | Error | Correct | Unlabeled | /2,241 | /2,225 candidates |','|---|---:|---:|---:|---:|---:|---:|---:|']
for x in flow['stages']:
 s.append(f"| {x['stage']} | {x['n_items']} | {x['source_groups']} | {x['support']['error']} | {x['support']['correct']} | {x['support']['unlabeled']} | {x['relative_to_manifest']:.3f} | {x['relative_to_mechanical_candidates']:.3f} |")
s += ['', 'Interpretation: `1,735/1,735` is only the strict analysis table’s internal feature/OOF coverage. Relative to all 2,225 mechanical candidates, strict analysis coverage is 1,735/2,225 = 77.98%; relative to the 2,241 manifest it is 77.42%. JSON-complete means a parsed JSON object was recorded for all three worlds, not that numeric answer, unit, and confidence parsing succeeded.', '', 'Failure flags are overlapping. The 16 identity-break candidates are not assigned a mutually exclusive semantic category; they are mechanically excluded from the request queue, while parser, label, and request failures may co-occur.']
open(D/'reports/QUEUE_FLOW_TABLE.md','w').write('\n'.join(s)+'\n')
# Performance table
order=['graph_only','two_world_hgb','three_world_hgb','three_world_curve_hgb','full','no_consistency','no_edit','no_numeric','no_reverse','shuffle','no_hgb']
by={x['method']:x for x in met['metrics']}; ci={x['comparison'].split(' - ')[0]:x for x in met['comparisons'] if ' - three_world_curve_hgb' in x['comparison']}
s=['# Saved PECR performance and ablations', '', 'All rows use the saved 1,735-item OOF universe (1,375 errors / 360 correct), 424 source groups, and coverage 100%. The Transformer rows are saved exploratory development outputs; the HGB rows are the audited zero-call recomputation.', '', '| Method | AUROC | AUPRC | Δ AUROC vs Curve | 95% source-group CI | Coverage | Role |','|---|---:|---:|---:|---|---:|---|']
roles={'graph_only':'structural baseline','two_world_hgb':'two-world HGB; positive/original response only','three_world_hgb':'ordinary three-world HGB','three_world_curve_hgb':'audited Curve HGB','full':'Transformer full','no_consistency':'Transformer ablation','no_edit':'Transformer ablation','no_numeric':'Transformer ablation','no_reverse':'Transformer ablation','shuffle':'Transformer shuffled-pair ablation','no_hgb':'Transformer without HGB branch'}
for n in order:
 x=by[n]; q=ci.get(n); d='—' if n=='three_world_curve_hgb' else f"{q['delta_auroc']:+.4f}" if q else '—'; cistr='—' if not q else f"[{q['source_group_bootstrap_ci95'][0]:+.4f}, {q['source_group_bootstrap_ci95'][1]:+.4f}]"
 s.append(f"| {n} | {x['auroc']:.4f} | {x['auprc']:.4f} | {d} | {cistr} | {x['coverage']:.1%} | {roles[n]} |")
s += ['', 'Additional saved comparison: two-world HGB − ordinary three-world HGB = −0.02565, 95% CI [−0.04280, −0.00914]. Curve HGB − ordinary three-world HGB = +0.01595, 95% CI [+0.00411, +0.02689] under the saved source-group bootstrap protocol (B=2,000, seed 20260928).', '', 'Caution: the source-group intervals quantify uncertainty conditional on fixed OOF predictions; they do not remove repeated development-set model-selection bias. Transformer ablation CIs are post hoc paired rechecks of saved OOF files, not preregistered confirmation tests.']
open(D/'reports/PERFORMANCE_AND_ABLATIONS.md','w').write('\n'.join(s)+'\n')
# verification report
s=['# Read-only implementation and evidence verification', '', '## Verified from saved artifacts', '', '- Ledger contains 6,675 records: 2,225 each for original/positive/negative; all HTTP 200; model identity is Qwen3.5-4B; hash-chain errors are empty; two records lack `parsed_json` and were retained without retry.', '- The audited Curve implementation reports GroupKFold(5), 424 source groups, positive class `original_incorrect=1`, HGB seed 20260928, and source-group bootstrap B=2,000, seed 20260928.', '- The implementation audit tests pass: named feature dimensions, independent arrays/no shared memory, negative-world invariance of two-world features, and preservation of curve features before/after fitting.', '- The saved OOF arrays all have n=1,735, matching labels and groups; the four HGB predictions are in one audited OOF file, so the reported HGB comparisons use the same rows and labels.', '- Static source review confirms the two-world vector is explicitly built from original/positive response quantities only, while curve features include negative response quantities. The code also constructs ordinary three-world and Curve feature matrices from the same parsed rows.', '- The original V1 results are preserved and the audit’s pre/post report records the change: two-world AUROC 0.7837→0.7722; ordinary three-world unchanged at 0.7978; Curve 0.8092→0.8138. This is a versioned discrepancy, not silently corrected historical output.', '', '## Not independently established', '', '- OOF provenance cannot be reconstructed from OOF files alone: they do not embed the full feature matrix, fold assignment file, or per-row training log. The code/report/hash chain provide evidence, but not a cryptographic proof that every saved prediction was generated by the current source.', '- The 50-item review directory contains a 50-item, response/label-blind packet and metadata (seed 20260928, 50 distinct source groups), but no reviewer identity source, completed form, disagreement log, or adjudication record was found in that directory. Therefore “50/50 VALID” is recorded only as project-lead reported, not independently verified by this audit.', '- Reverse-world semantic/financial validity for all 2,225 candidates is not established by the 50 reported judgments.']
open(D/'reports/IMPLEMENTATION_AND_EVIDENCE_REVIEW.md','w').write('\n'.join(s)+'\n')
# paper insertions
s=['# Paper-ready English insertions (with claim boundaries)', '', '## Data flow and coverage', '', 'We constructed a three-world development queue from 2,241 manifest items. A label-blind mechanical construction retained 2,225 candidates and excluded 16 items flagged by conservative identity checks. The retained candidates generated 6,675 requests (original, positive, and negative worlds); 6,673 records contained a parsed JSON payload, yielding 2,223 items with JSON present in all three worlds. After restricting to items with frozen correctness labels and strict numeric/confidence parsing, the final analysis set contained 1,735 items from 424 source groups (1,375 original-answer errors and 360 correct answers). Thus, the reported 1,735/1,735 feature coverage is conditional on the strict analysis set; it corresponds to 77.98% of the 2,225 mechanical candidates and 77.42% of the full 2,241-item manifest.', '', '## Main development results', '', 'Using fixed out-of-fold predictions on the 1,735-item development set, graph-only, two-world HGB, ordinary three-world HGB, and Curve HGB obtained AUROCs of 0.7275, 0.7722, 0.7978, and 0.8138, respectively; corresponding AUPRC values were 0.9032, 0.9201, 0.9308, and 0.9371. Curve HGB exceeded ordinary three-world HGB by 0.0160 AUROC, with a source-group bootstrap 95% interval of [0.0041, 0.0269] under the fixed OOF protocol. The two-world comparison was unfavorable relative to ordinary three-world HGB (−0.0256, 95% CI [−0.0428, −0.0091]), indicating that the additional reverse-world response contains useful signal in this development analysis.', '', '## Transformer exploratory results', '', 'A saved Transformer full model achieved AUROC 0.7924 and AUPRC 0.9265, below Curve HGB (0.8138/0.9371). Removing consistency, edit, numeric, or reverse components yielded AUROCs of 0.7914, 0.7915, 0.7924, and 0.7922, while shuffled pairing yielded 0.7926. These exploratory ablations do not provide clean evidence that the proposed Transformer mechanisms add value; the no-HGB ablation fell to 0.5247, underscoring that the neural model relied heavily on the HGB branch.', '', '## Limitations', '', 'These are repeatedly used development-set analyses rather than independent confirmation results. The reverse-world construction is mechanically generated and its semantic validity has only been assessed in a reported 50-item review outcome; the underlying reviewer records were not available for independent verification. We therefore present the results as evidence that program-conditioned multi-world response features are promising on this development queue, not as an independent generalization or state-of-the-art claim.']
open(D/'reports/PAPER_INSERTS_EN.md','w').write('\n'.join(s)+'\n')
# claims
s=['# Claim-permission checklist', '', '## Allowed with explicit qualifiers', '- “On the repeatedly used 1,735-item development analysis, Curve HGB had higher AUROC than ordinary three-world HGB.”', '- “The audited three-world Curve implementation passed the recorded zero-call array/invariance tests.”', '- “The dataset flow retained 2,225 mechanical candidates and 2,223 items with JSON present in all three worlds, before strict analysis reduced the set to 1,735.”', '- “The project lead reports 50/50 VALID in a blind review sample; the audit independently verifies only the existence and design of the blind packet.”', '', '## Do not claim from this audit', '- Do not call 1,735 items an independent test, confirmation set, or untouched holdout.', '- Do not claim all 2,225 reverse constructions are semantically or financially valid.', '- Do not claim Transformer superiority, mechanism-specific ablation support, or SOTA: the full Transformer is below Curve HGB and shuffled/no-mechanism ablations are close.', '- Do not report the V1 Curve value 0.8092 as the audited current result; preserve it only as a historical pre-audit value.', '- Do not claim the Curve confidence interval generalizes beyond the development queue or corrects repeated method selection.', '- Do not state 100% coverage without the denominator “within the strict 1,735-item analysis set.”']
open(D/'reports/CLAIM_CHECKLIST.md','w').write('\n'.join(s)+'\n')
# unresolved
s=['# Unresolved and non-auditable items', '', '1. The reviewer-completed forms, reviewer identities/independence, disagreement records, and adjudication record for the 50-item blind review were not present in the inspected review directory. The 50/50 VALID result remains project-lead reported.', '2. The full mechanical-candidate exclusion rationale for the 16 identity-break items is available as construction flags, but the flags are conservative mechanical checks, not proof that the underlying source table is invalid.', '3. The 490 mechanical candidates absent from the strict feature table cannot be assigned a single failure cause without conflating overlapping label, parse, JSON, and construction statuses; the item-level audit preserves these as separate flags.', '4. The saved OOF arrays do not include a self-contained fold manifest or feature snapshot. Reproducibility is supported by code, hashes, and reports but not fully independently reconstructible from OOF files alone.', '5. No claim about the 565-item holdout is made here; it was not read or used in this audit.']
open(D/'reports/UNRESOLVED_ITEMS.md','w').write('\n'.join(s)+'\n')
# final output hashes
files=[]
for p in sorted(D.rglob('*')):
 if p.is_file() and p.name!='SHA256SUMS_OUTPUTS.txt': files.append(p)
with open(D/'reports/SHA256SUMS_OUTPUTS.txt','w') as f:
 for p in files:
  h=hashlib.sha256(p.read_bytes()).hexdigest(); f.write(f'{h}  {p.relative_to(D)}\n')
